version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Resolve dependencies
          command: |
            npm dedupe
            npm ls react react-dom
      - store_test_results:
          path: ./test-results/
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Resolve dependencies
          command: npm dedupe
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  code-analysis:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run ESLint (simulation)
          command: echo "Simulating ESLint analysis..."
      - run:
          name: Run TypeScript compiler check (simulation)
          command: echo "Simulating TypeScript check..."
  clean-and-package:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Clean previous build (simulation)
          command: echo "Simulating cleaning of previous build..."
      - run:
          name: Build Next.js application (simulation)
          command: echo "Simulating Next.js build process..."
      - persist_to_workspace:
          root: .
          paths:
            - .
# STAGE POUR LES TESTS
  unit-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests (simulation)
          command: echo "Simulating unit tests execution..."
  integration-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run integration tests (simulation)
          command: echo "Simulating integration tests execution..."
  regression-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run regression tests (simulation)
          command: echo "Simulating regression tests execution..."
  performance-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run performance tests (simulation)
          command: echo "Simulating performance tests execution..."
  security-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run security tests (simulation)
          command: echo "Simulating security tests execution..."
  compatibility-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run compatibility tests (simulation)
          command: echo "Simulating compatibility tests execution..."
  accessibility-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run accessibility tests (simulation)
          command: echo "Simulating accessibility tests execution..."
#stage DEPLOY
  prepare-deploy-env:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prepare deployment environment (simulation)
          command: |
            echo "Simulating environment preparation for branch: ${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo "Preparing development environment"
            elif [ "${CIRCLE_BRANCH}" == "integration" ]; then
              echo "Preparing integration environment"
            elif [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "Preparing production environment"
            fi
  deploy-application:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy application (simulation)
          command: |
            echo "Simulating deployment for branch: ${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo "Deploying to development server"
            elif [ "${CIRCLE_BRANCH}" == "integration" ]; then
              echo "Deploying to integration server"
            elif [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "Deploying to production server"
            fi
  verification-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run verification tests (simulation)
          command: echo "Simulating verification tests after deployment..."
  functional-validation:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run functional validation tests (simulation)
          command: echo "Simulating functional validation tests..."
  load-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run load tests (simulation)
          command: echo "Simulating load tests on deployed application..."
  final-deployment:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Finalize deployment (simulation)
          command: echo "Simulating final deployment steps..."
  monitoring-setup:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set up monitoring (simulation)
          command: echo "Simulating monitoring and alerting setup..."
workflows:
  build-test-deploy:
    jobs:
#Excecuter sur toutes les branches
      - install-dependencies
      - code-analysis:
          requires:
            - install-dependencies
      - clean-and-package:
          requires:
            - code-analysis
      - unit-tests:
          requires:
            - clean-and-package
      - integration-tests:
          requires:
            - clean-and-package
          filters:
            branches:
              ignore: /^(feature|hotfix).*/
#Stage des tests
      - regression-tests:
          requires:
            - clean-and-package
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - performance-tests:
          requires:
            - clean-and-package
          filters:
            branches:
              only:
                - integration
                - main
      - security-tests:
          requires:
            - clean-and-package
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - compatibility-tests:
          requires:
            - clean-and-package
          filters:
            branches:
              only:
                - integration
                - main
      - accessibility-tests:
          requires:
            - clean-and-package
          filters:
            branches:
              only:
                - integration
                - main
#Stage de déploiement
      - prepare-deploy-env:
          name: prepare-dev-env
          requires:
            - unit-tests
          filters:
            branches:
              only:
                - develop
                - integration
                - main
                
      - deploy-application:
          requires:
            - prepare-dev-env
            - integration-tests
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - verification-tests:
          requires:
            - deploy-application
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - functional-validation:
          requires:
            - verification-tests
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - load-tests:
          requires:
            - functional-validation
          filters:
            branches:
              only:
                - integration
                - main
      - final-deployment:
          requires:
            - load-tests
          filters:
            branches:
              only:
                - integration
                - main
      - monitoring-setup:
          requires:
            - final-deployment
          filters:
            branches:
              only:
                - integration
                - main
