version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Resolve dependencies
          command: |
            npm dedupe
            npm ls react react-dom
      - store_test_results:
          path: ./test-results/
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Resolve dependencies
          command: npm dedupe
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  code-analysis:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run ESLint (simulation)
          command: echo "Simulating ESLint analysis..."
      - run:
          name: Run TypeScript compiler check (simulation)
          command: echo "Simulating TypeScript check..."
  clean-and-package:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Clean previous build (simulation)
          command: echo "Simulating cleaning of previous build..."
      - run:
          name: Build Next.js application (simulation)
          command: echo "Simulating Next.js build process..."
      - persist_to_workspace:
          root: .
          paths:
            - .
  # STAGE POUR LES TESTS
  unit-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests (simulation)
          command: echo "Simulating unit tests execution..."
  integration-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run integration tests (simulation)
          command: echo "Simulating integration tests execution..."
  regression-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run regression tests (simulation)
          command: echo "Simulating regression tests execution..."
  performance-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run performance tests (simulation)
          command: echo "Simulating performance tests execution..."
  compatibility-tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run compatibility tests (simulation)
          command: echo "Simulating compatibility tests execution..."
workflows:
  build-and-test:
    jobs:
      - test-node
      - install-dependencies
      - code-analysis
      - clean-and-package
      - unit-tests
      - integration-tests
      - regression-tests
      - performance-tests
      - compatibility-tests