version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Resolve dependencies
          command: |
            npm dedupe
            npm ls react react-dom
      - store_test_results:
          path: ./test-results/
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Resolve dependencies
          command: npm dedupe
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  code-analysis:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run ESLint
          command: npx eslint . --max-warnings=0 || echo "ESLint issues found"
      - run:
          name: Run TypeScript compiler check
          command: npx tsc --noEmit || echo "TypeScript issues found"
      - store_artifacts:
          path: ./reports
          destination: code-analysis-reports
  clean-and-package:
  executor: node/default
  steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Clean previous build
        command: rm -rf .next || true
    - run:
        name: Build Next.js application
        command: npm run build
    - persist_to_workspace:
        root: .
        paths:
          - .next
          - public
          - package.json
          - node_modules
workflows:
  build-and-test:
    jobs:
      - test-node
      - install-dependencies
      - code-analysis
      - clean-and-package